// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(BangazonDbContext))]
    [Migration("20240831155527_MigrationName")]
    partial class MigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BackEnd.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2015),
                            Description = "A cozy, hand-knitted scarf made from 100% organic wool. Perfect for chilly days.",
                            Image = "https://i.ytimg.com/vi/aOPXU_3maSE/sddefault.jpg",
                            Price = 45.00m,
                            QuantityAvailable = 25,
                            SellerId = 1,
                            Title = "Hand Knit Scarf"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2011),
                            Description = "A set of three homemade soy candles with natural scents like lavender, vanilla, and cinnamon.",
                            Image = "https://i.ebayimg.com/images/g/1yIAAOSwNmJhf4Ch/s-l1200.jpg",
                            Price = 30.00m,
                            QuantityAvailable = 25,
                            SellerId = 1,
                            Title = "Homemade Soy Candles"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2006),
                            Description = "Set of four handcrafted wooden coasters, made from reclaimed wood. Each coaster is unique.",
                            Image = "https://assets.bigcartel.com/product_images/233112323/coast+1+.jpg?auto=format&fit=max&w=1500",
                            Price = 19.99m,
                            QuantityAvailable = 40,
                            SellerId = 1,
                            Title = "Wooden Coasters"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2004),
                            Description = "Organic, homemade herbal soap infused with essential oils. Gentle on skin and eco-friendly.",
                            Image = "https://lovelygreens.com/wp-content/uploads/herbal-soap-calendula.jpg",
                            Price = 10.00m,
                            QuantityAvailable = 15,
                            SellerId = 1,
                            Title = "Herbal Soap"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1996),
                            Description = "A pair of hand-painted ceramic mugs with unique designs. Dishwasher and microwave safe.",
                            Image = "https://kariceramics.com/cdn/shop/products/Kari_ceramics_handmade_pottery_all_ceramic_mugs.jpg?v=1625917134",
                            Price = 35.00m,
                            QuantityAvailable = 25,
                            SellerId = 1,
                            Title = "Ceramic Mugs"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2024, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A beautifully handcrafted wooden bowl made from reclaimed oak wood. Perfect for serving salads or as a decorative piece.",
                            Image = "https://m.media-amazon.com/images/I/71A6SYOZwVL._AC_UF894,1000_QL80_.jpg",
                            Price = 35.99m,
                            QuantityAvailable = 12,
                            SellerId = 1,
                            Title = "Handcrafted Wooden Bowl"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Handcrafted beaded dog collar made with durable leather and colorful, intricate beadwork. A unique accessory that adds style and comfort for your furry friend.",
                            Image = "https://swdistinctions.com/wp-content/uploads/2016/06/sw-mountain-collar-unnamed.png",
                            Price = 24.99m,
                            QuantityAvailable = 20,
                            SellerId = 1,
                            Title = "Handmade Beaded Dog Collar"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A unique ceramic coffee mug, handcrafted and glazed in vibrant colors. Dishwasher and microwave safe.",
                            Image = "https://stellancworks.com/cdn/shop/products/20220406_125939_1024x1024@2x.jpg?v=1652184454",
                            Price = 18.50m,
                            QuantityAvailable = 30,
                            SellerId = 1,
                            Title = "Ceramic Coffee Mug"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Handmade leather-bound journal with recycled paper. Perfect for writing, sketching, or as a diary.",
                            Image = "https://www.galenleather.com/cdn/shop/products/refillable-leather-wrap-journal-planner-cover-crazy-horse-brown_2000x.jpg?v=1622296261",
                            Price = 45.00m,
                            QuantityAvailable = 15,
                            SellerId = 1,
                            Title = "Leather Journal"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An elegant vase made from recycled glass, with a unique texture and shape. A great centerpiece for any room.",
                            Image = "https://i.ebayimg.com/images/g/FaUAAOSwcQdjka-Z/s-l400.jpg",
                            Price = 32.75m,
                            QuantityAvailable = 8,
                            SellerId = 1,
                            Title = "Recycled Glass Vase"
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable and eco-friendly, this bamboo cutting board is handmade and treated with natural oils for a long-lasting finish.",
                            Image = "https://m.media-amazon.com/images/I/A16Lps3fycL._UF1000,1000_QL80_.jpg",
                            Price = 27.99m,
                            QuantityAvailable = 25,
                            SellerId = 1,
                            Title = "Bamboo Cutting Board"
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A luxurious hand-painted silk scarf with floral motifs. Lightweight and perfect for all seasons.",
                            Image = "https://invisibleworld.com/cdn/shop/products/invisible-world-long-hand-painted-silk-scarf-monochrome-flowers-29200750608453_813x.jpg?v=1629674715",
                            Price = 65.00m,
                            QuantityAvailable = 10,
                            SellerId = 1,
                            Title = "Hand-Painted Silk Scarf"
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hand-poured soy wax candle with a refreshing lavender scent. Burns cleanly and lasts up to 40 hours.",
                            Image = "https://i5.walmartimages.com/asr/85ea12b1-ecb7-431e-bb11-bfa665a31981.a444b21c5cc1654ad3b0f3fcb87b816f.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
                            Price = 15.50m,
                            QuantityAvailable = 40,
                            SellerId = 1,
                            Title = "Natural Soy Wax Candle"
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A boho-inspired macramé wall hanging, hand-knotted with natural cotton rope. Adds a rustic touch to any home decor.",
                            Image = "https://m.media-amazon.com/images/I/91IQzXWHmQL.jpg",
                            Price = 55.00m,
                            QuantityAvailable = 7,
                            SellerId = 1,
                            Title = "Macramé Wall Hanging"
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(2024, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set of three hand-carved wooden spoons made from sustainably sourced walnut wood. Perfect for cooking and serving.",
                            Image = "https://images.squarespace-cdn.com/content/v1/5cb5bc4b7fdcb821197daa93/1676901378771-2J0XFNJ49RX8PL7XG1NB/Spoon+Set+with+Spoon+Rack2.jpeg?format=2500w",
                            Price = 30.00m,
                            QuantityAvailable = 16,
                            SellerId = 1,
                            Title = "Hand-Carved Wooden Spoon Set"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Seller")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Image = "",
                            Seller = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
